import { font, radii } from "@madhuban/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: "#EEF2F8",
  },
  heroWrap: {
    overflow: "hidden",
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    paddingHorizontal: 16,
    paddingBottom: 20,
    minHeight: 196,
  },
  heroWrapCompact: {
    paddingBottom: 16,
    minHeight: 182,
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  eyebrowPill: {
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.10)",
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  eyebrowText: {
    color: "rgba(241,245,255,0.88)",
    fontFamily: font.family.bold,
    fontSize: 11,
    letterSpacing: 1.2,
    textTransform: "uppercase",
  },
  notifyButton: {
    width: 42,
    height: 42,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.14)",
    backgroundColor: "rgba(255,255,255,0.08)",
    alignItems: "center",
    justifyContent: "center",
  },
  notifyDot: {
    position: "absolute",
    top: 8,
    right: 9,
    width: 9,
    height: 9,
    borderRadius: radii.full,
    backgroundColor: "#E04F5F",
    borderWidth: 1,
    borderColor: "#202C43",
  },
  title: {
    marginTop: 16,
    color: "#FCFEFF",
    fontFamily: font.family.black,
    fontSize: 26,
    lineHeight: 31,
    letterSpacing: -0.7,
  },
  titleCompact: {
    marginTop: 14,
    fontSize: 23,
    lineHeight: 27,
  },
  subtitleRow: {
    marginTop: 8,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  subtitleRowCompact: {
    marginTop: 6,
  },
  subtitle: {
    flex: 1,
    color: "rgba(226,233,246,0.78)",
    fontFamily: font.family.medium,
    fontSize: 13,
    lineHeight: 18,
  },
  subtitleCompact: {
    fontSize: 12,
    lineHeight: 16,
  },
  headerCard: {
    marginTop: 14,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.07)",
    padding: 12,
  },
  headerCardCompact: {
    marginTop: 10,
    padding: 10,
  },
  body: {
    flex: 1,
    marginTop: -14,
    borderTopLeftRadius: radii.xl,
    borderTopRightRadius: radii.xl,
    backgroundColor: "#F6F8FC",
    paddingHorizontal: 16,
    paddingTop: 14,
  },
  bodyCompact: {
    marginTop: -12,
    paddingTop: 12,
  },
  heroGlowBlue: {
    position: "absolute",
    width: 170,
    height: 170,
    borderRadius: radii.full,
    backgroundColor: "rgba(86, 123, 251, 0.18)",
    top: -30,
    right: -20,
  },
  heroGlowDark: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: radii.full,
    backgroundColor: "rgba(9, 18, 33, 0.28)",
    left: -85,
    bottom: -110,
  },
});
