export {
  configureApiBaseUrl,
  getApiBaseUrl,
  getDevTokenFallback,
  allowDemo404Fallback,
} from "./env";
export { configureAuthTokenGetter, getAuthHeaders, readJsonOrThrow } from "./client";
export { login, type LoginResult } from "./auth";
export {
  normalizeMobile,
  mobileLogin,
  requestOtp,
  verifyOtp,
  resetPasswordWithOtp,
} from "./mobileAuth";
export {
  getTasks,
  getTaskById,
  createTask,
  updateTask,
  updateTaskStatus,
  deleteTask,
  approveTask,
  rejectTask,
  normalizeTask,
  type TaskFilters,
  getMasterTasks,
  type MasterTaskRecord,
  getMasterTaskById,
  getStaffMasterTasks,
  assignStaffMasterTask,
  type StaffMasterTaskRecord,
  runDailyTasksCron,
  getDailyStaffTasks,
  type DailyStaffTaskRecord,
} from "./tasks";
export {
  getAdminDashboard,
  type AdminDashboardResponse,
  getDashboardMetrics,
  getSalesPipeline,
  getRevenue,
  getAlerts,
  getActivity,
} from "./dashboard";
export {
  getUsers,
  getUsersForAssignee,
  getSupervisors,
  getManagers,
  getStaffUsers,
  getUserById,
  createUser,
  updateUser,
  deleteUser,
  resetPassword,
  getRoles,
  getDepartments,
  getDepartmentById,
  type ManagerRecord,
  type RoleRecord,
  type SupervisorRecord,
} from "./users";
export {
  getProperties,
  getPropertyById,
  getPropertyWithFloors,
  getPropertyFloors,
  getPropertyFloorZones,
  createProperty,
  updateProperty,
  deleteProperty,
  getPropertySummary,
} from "./properties";
export {
  getCurrentUser,
  changePassword,
  updateUserProfile,
  getMyTasks,
  getMyTaskById,
  updateMyTaskStatus,
  startMyTask,
  submitMyTaskCompletion,
  checkIn,
  checkOut,
  getTodayAttendance,
} from "./endUser";
export {
  getStaffProfile,
  getStaffDashboard,
  getStaffAttendance,
  submitStaffAttendance,
  getStaffTasks,
  uploadStaffTaskBeforePhoto,
  uploadStaffTaskAfterPhoto,
  getStaffReport,
  type StaffProfileResponse,
  type StaffDashboardResponse,
  type StaffAttendanceResponse,
  type StaffAttendanceSubmitPayload,
  type StaffTasksResponse,
  type StaffTaskFilters,
  type StaffReportResponse,
} from "./staff";
export {
  getSupervisorDashboard,
  getSupervisorAttendance,
  submitSupervisorAttendance,
  getSupervisorShiftReport,
  getSupervisorEmployeeShiftReport,
  getSupervisorReviews,
  getSupervisorReviewDetail,
  submitSupervisorReviewDecision,
  getSupervisorDailyStaffTasks,
  type SupervisorDashboardResponse,
  type SupervisorAttendanceResponse,
  type SupervisorAttendanceSubmitPayload,
  type UploadableFile,
  type SupervisorShiftReportResponse,
  type SupervisorEmployeeShiftReportResponse,
  type SupervisorReviewsResponse,
  type SupervisorReviewDetailResponse,
  type SupervisorReviewDecisionPayload,
  type SupervisorReviewDecisionResponse,
  type SupervisorReviewFilters,
} from "./supervisor";
export {
  getManagerDashboard,
  getManagerAttendance,
  submitManagerAttendance,
  getManagerProfile,
  getManagerTasks,
  getManagerSupervisors,
  getManagerShiftReport,
  getManagerEmployeeShiftReport,
  submitManagerReviewDecision,
  type ManagerDashboardResponse,
  type ManagerAttendanceResponse,
  type ManagerAttendanceSubmitPayload,
  type ManagerProfileResponse,
  type ManagerTasksResponse,
  type ManagerSupervisorRecord,
  type ManagerTaskFilters,
  type ManagerShiftReportResponse,
  type ManagerEmployeeShiftReportResponse,
  type ManagerReviewDecisionPayload,
  type ManagerReviewDecisionResponse,
} from "./manager";
