import { colors, font, radii } from "@madhuban/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  scroll: {
    flex: 1,
  },
  content: {
    gap: 10,
    paddingBottom: 14,
  },
  shiftStatusCard: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 12,
  },
  shiftStatusBlock: {
    flex: 1,
    gap: 4,
  },
  shiftDateBlock: {
    width: 82,
    alignItems: "flex-end",
    justifyContent: "space-between",
  },
  shiftStatusLabel: {
    color: "rgba(225,233,245,0.72)",
    fontFamily: font.family.bold,
    fontSize: 10,
    letterSpacing: 1.1,
    textTransform: "uppercase",
  },
  shiftStatusRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  statusDot: {
    width: 9,
    height: 9,
    borderRadius: radii.full,
    backgroundColor: "#30D19B",
  },
  shiftStatusValue: {
    color: "#FFFFFF",
    fontFamily: font.family.bold,
    fontSize: 15,
  },
  shiftStatusDate: {
    color: "#FFFFFF",
    fontFamily: font.family.bold,
    fontSize: 13,
  },
  heroDivider: {
    width: 1,
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 24,
    padding: 13,
    borderWidth: 1,
    borderColor: "#E8EDF4",
    shadowColor: "rgba(25, 41, 66, 0.08)",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 3,
    gap: 10,
  },
  sectionTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sectionTitleLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitle: {
    color: "#6C7B93",
    fontFamily: font.family.bold,
    fontSize: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  sectionAction: {
    color: colors.primary,
    fontFamily: font.family.bold,
    fontSize: 11,
  },
  loaderWrap: {
    minHeight: 68,
    alignItems: "center",
    justifyContent: "center",
  },
  progressRow: {
    flexDirection: "row",
    gap: 10,
  },
  progressRing: {
    width: 74,
    height: 74,
    borderRadius: radii.full,
    borderWidth: 4,
    borderColor: "#2667FF",
    alignItems: "center",
    justifyContent: "center",
  },
  progressRingValue: {
    color: colors.text,
    fontFamily: font.family.black,
    fontSize: 22,
    lineHeight: 24,
  },
  progressRingLabel: {
    marginTop: 1,
    color: "#8B98AB",
    fontFamily: font.family.bold,
    fontSize: 9,
    textTransform: "uppercase",
  },
  progressMetric: {
    flex: 1,
    borderRadius: 18,
    backgroundColor: "#F4F7FB",
    paddingHorizontal: 10,
    paddingVertical: 11,
    justifyContent: "center",
    gap: 3,
  },
  progressMetricValue: {
    color: colors.text,
    fontFamily: font.family.black,
    fontSize: 23,
    lineHeight: 25,
  },
  progressMetricLabel: {
    color: "#8190A6",
    fontFamily: font.family.bold,
    fontSize: 9,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  alertCard: {
    borderRadius: 20,
    paddingHorizontal: 13,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    borderWidth: 1,
  },
  alertCardDanger: {
    backgroundColor: "#FFF7F8",
    borderColor: "#FFDADF",
  },
  alertCardInfo: {
    backgroundColor: "#FBF7FF",
    borderColor: "#ECDFFF",
  },
  alertIconWrap: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  alertBody: {
    flex: 1,
    gap: 2,
  },
  alertEyebrow: {
    fontFamily: font.family.bold,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  alertTitle: {
    color: colors.text,
    fontFamily: font.family.bold,
    fontSize: 16,
    lineHeight: 20,
  },
  alertHint: {
    color: colors.textMuted,
    fontFamily: font.family.medium,
    fontSize: 10,
  },
  approvalGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: -4,
  },
  heroStat: {
    width: "50%",
    paddingHorizontal: 4,
    paddingVertical: 8,
    alignItems: "center",
    gap: 4,
  },
  heroStatValue: {
    fontFamily: font.family.black,
    fontSize: 26,
    lineHeight: 28,
  },
  heroStatLabel: {
    color: "#72829A",
    fontFamily: font.family.bold,
    fontSize: 9,
    letterSpacing: 0.9,
    textTransform: "uppercase",
  },
});
