import { colors, font, radii, space } from "@madhuban/theme";
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F1F3F7",
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingBottom: 26,
  },
  contentWithTopSpacing: {
    paddingTop: 14,
  },
  heroCard: {
    overflow: "hidden",
    borderBottomLeftRadius: 32,
    borderBottomRightRadius: 32,
    paddingHorizontal: 16,
    paddingBottom: 16,
    backgroundColor: "#1D2C43",
    shadowColor: "rgba(20, 31, 47, 0.34)",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 1,
    shadowRadius: 22,
    elevation: 14,
  },
  heroGradient: {
    ...StyleSheet.absoluteFillObject,
  },
  heroGlowTop: {
    position: "absolute",
    top: -54,
    right: -22,
    width: 164,
    height: 164,
    borderRadius: radii.full,
    backgroundColor: "rgba(73, 115, 206, 0.24)",
  },
  heroGlowBottom: {
    position: "absolute",
    left: -110,
    bottom: -120,
    width: 248,
    height: 248,
    borderRadius: radii.full,
    backgroundColor: "rgba(8, 16, 30, 0.34)",
  },
  heroTopRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  sitePill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.full,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.10)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  sitePillText: {
    color: "#C8D3E8",
    fontFamily: font.family.bold,
    fontSize: 10,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  heroActions: {
    alignItems: "center",
    gap: 10,
  },
  avatarCard: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#FF9500",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "rgba(255, 149, 0, 0.45)",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 10,
  },
  avatarText: {
    color: "#FFFFFF",
    fontFamily: font.family.black,
    fontSize: 16,
    lineHeight: 18,
    letterSpacing: -0.2,
  },
  notificationCard: {
    width: 34,
    height: 34,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.12)",
    backgroundColor: "rgba(255,255,255,0.08)",
  },
  notificationDot: {
    position: "absolute",
    top: 7,
    right: 7,
    width: 8,
    height: 8,
    borderRadius: radii.full,
    backgroundColor: "#FF4E5F",
    borderWidth: 1,
    borderColor: "#20334E",
  },
  heroTitle: {
    marginTop: 8,
    color: "#F6F8FB",
    fontFamily: font.family.black,
    fontSize: 25,
    lineHeight: 30,
    letterSpacing: -0.8,
  },
  heroStatusRow: {
    marginTop: 6,
    flexDirection: "row",
    alignItems: "center",
    gap: 7,
  },
  heroStatusDot: {
    width: 7,
    height: 7,
    borderRadius: radii.full,
    backgroundColor: "#17BF7A",
  },
  heroStatusText: {
    color: "#BAC6D9",
    fontFamily: font.family.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  roleChip: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    backgroundColor: "#2958A5",
  },
  roleChipText: {
    color: "#91BCFF",
    fontFamily: font.family.bold,
    fontSize: 9,
    letterSpacing: 0.7,
  },
  summaryRow: {
    marginTop: 16,
    flexDirection: "row",
    gap: 10,
  },
  summaryStat: {
    flex: 1,
    overflow: "hidden",
    alignItems: "center",
    gap: 4,
    borderRadius: 18,
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "rgba(210,220,235,0.10)",
    backgroundColor: "rgba(255,255,255,0.10)",
  },
  summaryStatShine: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: "rgba(219, 229, 243, 0.55)",
  },
  summaryValue: {
    fontFamily: font.family.black,
    fontSize: 31,
    lineHeight: 34,
    letterSpacing: -0.8,
  },
  summaryLabel: {
    color: "#D4DBE8",
    fontFamily: font.family.bold,
    fontSize: 9,
    lineHeight: 11,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  body: {
    paddingHorizontal: 14,
    paddingTop: 14,
    gap: 14,
  },
  card: {
    borderRadius: 22,
    padding: 16,
    backgroundColor: colors.surfaceElevated,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "rgba(34, 50, 72, 0.10)",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 1,
    shadowRadius: 18,
    elevation: 4,
    gap: 14,
  },
  sectionBlock: {
    gap: 12,
  },
  sectionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  sectionTitleWrap: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionTitlePrimary: {
    color: "#28344B",
    fontFamily: font.family.bold,
    fontSize: 14,
    lineHeight: 18,
  },
  sectionTitleSecondary: {
    color: "#72809A",
    fontFamily: font.family.bold,
    fontSize: 11,
    lineHeight: 14,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  sectionAction: {
    color: "#286CFF",
    fontFamily: font.family.bold,
    fontSize: 11,
    lineHeight: 14,
  },
  attendanceActionList: {
    gap: 10,
  },
  attendanceActionCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E8EDF4",
    backgroundColor: "#F8FAFD",
    padding: space.md,
  },
  attendanceActionIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#E8F1FF",
    borderWidth: 1,
    borderColor: "#D7E5FF",
  },
  attendanceActionBody: {
    flex: 1,
    gap: 3,
  },
  attendanceActionTitle: {
    color: colors.text,
    fontFamily: font.family.bold,
    fontSize: 14,
  },
  attendanceActionSubtitle: {
    color: colors.textMuted,
    fontFamily: font.family.medium,
    fontSize: 11,
    lineHeight: 15,
  },
  attendanceActionButton: {
    minWidth: 72,
    borderRadius: radii.full,
    backgroundColor: colors.primary,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: "center",
    justifyContent: "center",
  },
  attendanceActionButtonText: {
    color: "#FFFFFF",
    fontFamily: font.family.bold,
    fontSize: 12,
  },
  progressPercent: {
    color: "#286CFF",
    fontFamily: font.family.black,
    fontSize: 23,
    lineHeight: 25,
    letterSpacing: -0.4,
  },
  progressTrack: {
    height: 6,
    borderRadius: radii.full,
    backgroundColor: "#E8ECF2",
    overflow: "hidden",
  },
  progressFill: {
    width: "62%",
    height: "100%",
    borderRadius: radii.full,
    backgroundColor: "#529BFF",
  },
  progressLegend: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  legendDot: {
    width: 6,
    height: 6,
    borderRadius: radii.full,
  },
  legendText: {
    color: "#5F6F87",
    fontFamily: font.family.medium,
    fontSize: 11,
    lineHeight: 14,
  },
  attentionGrid: {
    flexDirection: "row",
    gap: 12,
  },
  attentionCard: {
    flex: 1,
    minHeight: 108,
    borderRadius: 18,
    padding: 14,
    backgroundColor: "#FFFFFF",
    borderWidth: 1,
    borderColor: "#E9EDF5",
    shadowColor: "rgba(34, 50, 72, 0.08)",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 1,
    shadowRadius: 16,
    elevation: 3,
    gap: 8,
  },
  attentionStatus: {
    fontFamily: font.family.black,
    fontSize: 10,
    lineHeight: 12,
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  attentionStatusDanger: {
    color: "#FF3D45",
  },
  attentionStatusWarning: {
    color: "#FF8B00",
  },
  attentionTitle: {
    color: "#243149",
    fontFamily: font.family.bold,
    fontSize: 16,
    lineHeight: 20,
    letterSpacing: -0.3,
  },
  assigneeRow: {
    marginTop: "auto",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  assigneeBadge: {
    minWidth: 20,
    height: 20,
    borderRadius: 6,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#EEF2F8",
  },
  assigneeBadgeText: {
    color: "#60718B",
    fontFamily: font.family.bold,
    fontSize: 8,
    lineHeight: 10,
  },
  assigneeName: {
    color: "#7B879B",
    fontFamily: font.family.medium,
    fontSize: 11,
    lineHeight: 14,
  },
  zoneGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  zoneTile: {
    width: "48.4%",
    borderRadius: 15,
    paddingHorizontal: 12,
    paddingVertical: 13,
    backgroundColor: "#F8FAFC",
    borderWidth: 1,
    borderColor: "#EEF2F6",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  zoneTitle: {
    flex: 1,
    color: "#303D54",
    fontFamily: font.family.bold,
    fontSize: 13,
    lineHeight: 16,
  },
  zoneMetric: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  zoneValue: {
    color: "#2E394F",
    fontFamily: font.family.medium,
    fontSize: 11,
    lineHeight: 14,
  },
  zoneDot: {
    width: 8,
    height: 8,
    borderRadius: radii.full,
  },
  activityList: {
    gap: 16,
  },
  activityRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  activityRail: {
    alignItems: "center",
    width: 22,
  },
  activityIconWrap: {
    width: 20,
    height: 20,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
  },
  activityIconSuccess: {
    backgroundColor: "#EEFCEF",
    borderWidth: 1,
    borderColor: "#CBF2D2",
  },
  activityIconMuted: {
    backgroundColor: "#EFF3F8",
    borderWidth: 1,
    borderColor: "#DFE6EF",
  },
  activityLine: {
    width: 1,
    flex: 1,
    marginTop: 6,
    backgroundColor: "#E5EAF2",
  },
  activityBody: {
    flex: 1,
    gap: 4,
  },
  activityHeadline: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 8,
  },
  activityStatus: {
    color: "#26354C",
    fontFamily: font.family.bold,
    fontSize: 18,
    lineHeight: 22,
    letterSpacing: -0.3,
  },
  activityTime: {
    color: "#B1BAC8",
    fontFamily: font.family.medium,
    fontSize: 10,
    lineHeight: 12,
  },
  activityDetail: {
    color: "#66758C",
    fontFamily: font.family.medium,
    fontSize: 12,
    lineHeight: 16,
  },
  activityAssignee: {
    color: "#2C69FF",
    fontFamily: font.family.medium,
  },
  activityNotePill: {
    alignSelf: "flex-start",
    marginTop: 2,
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 5,
    backgroundColor: "#FFF1F0",
  },
  activityNoteText: {
    color: "#E24A4F",
    fontFamily: font.family.bold,
    fontSize: 10,
    lineHeight: 12,
  },
});
